services:
  joyapi:
    container_name: joy-api
    image: joyapi
    depends_on:
      - db
    ports:
      - 5026:5026
      - 7128:7128
      - 12760:12760
      - 8081:8081
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-network
  
  db:
    container_name: azure-sql-edge
    image: mcr.microsoft.com/azure-sql-edge
    cap_add: [ 'SYS_PTRACE' ]
    ports:
      - 1433:1433
    restart: always
    volumes:
      - ./db_volume:/var/opt/mssql
    environment:
      MSSQL_SA_PASSWORD: "Password0"
      ACCEPT_EULA: "Y"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge