services:
  joy-api:
    container_name: joy-api
    build:
      context: "."
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    ports:
      - 5026:5026
      - 7128:7128
      - 12760:12760
      - 8081:8081
      - 8080:8080
    entrypoint:
      - "dotnet"
      - "/app/bin/Debug/net8.0/JoyApi.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    image: "joyapi"
    depends_on:
      - azure-sql-edge
    volumes:
      - "/Users/mb/Projects/joy-dotnet-api/src:/app:rw"
      - "/Users/mb/Projects/joy-dotnet-api/src:/src:rw"
      - "/Users/mb/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
    networks:
      - my-network
  
  azure-sql-edge:
    container_name: azure-sql-edge
    image: mcr.microsoft.com/azure-sql-edge
    cap_add: [ 'SYS_PTRACE' ]
    ports:
      - 1433:1433
    restart: always
    volumes:
      - ./db_volume:/var/opt/mssql
    environment:
      MSSQL_SA_PASSWORD: "Password0"
      ACCEPT_EULA: "Y"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge